apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: lab8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: campusconnect-product-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://202512088_db_user:7WGLZwHj98byShzI@cluster0.a8mct.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
